# Generated by Django 6.1.1 on 2026-09-09 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='নোটের নাম')),
                ('student_class', models.CharField(choices=[('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('Class 11', 'Class 11'), ('Class 12', 'Class 12')], max_length=20, verbose_name='ক্লাস')),
                ('subject', models.CharField(max_length=100, verbose_name='বিষয়')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('pdf_file', models.FileField(upload_to='notes_pdf/', verbose_name='পিডিএফ ফাইল')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='আপলোড তারিখ')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
